#!/bin/bash

set -e
cd "$(dirname "$0")"

dbdir="$PWD/repo"

echo "==> Setting up a package database"
repo-add "$dbdir/spacefox.db.tar.gz" "$dbdir"/*.pkg.tar.*

echo "==> Replacing symlinks"
(
  cd "$dbdir"
  for file in *.db *.files; do
    cp --remove-destination "$(readlink "$file")" "$file"
  done
)
