name: Build Package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
#      isAur:
#        required: true
#        type: boolean
      skipRuntimeDeps:
        type: boolean
        default: false
        required: false
      maxSpace:
        type: boolean
        default: false
        required: false
        
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: "Name of package to build"
        type: string
#      isAur:
#        required: true
#        description: "Is package part of the AUR?"
#        type: boolean
      skipRuntimeDeps:
        description: "Skip installation on runtime dependencies?"
        type: boolean
        default: false
        required: false
      maxSpace:
        description: "Maximize space on runner?"
        type: boolean
        default: false
        required: false
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        if: ${{inputs.maxSpace}}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 2048
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
            
      - name: Get Patches
        uses: actions/checkout@v4
        
      - name: Get PKGBUILD - AUR
#        if: ${{inputs.isAur}}
        run: git clone https://aur.archlinux.org/${{inputs.package}}.git

#      - name: Get PKGBUILD - Arch Gitlab
#        if: ${{!inputs.isAur}}
#        run: git clone https://gitlab.archlinux.org/archlinux/packaging/packages/${{inputs.package}}.git

      - name: Patch sources
        run: |
            cd ${{inputs.package}}
            [ -f "../${{inputs.package}}-patch/PKGBUILD.patch" ] && cp ../${{inputs.package}}-patch/* . && patch -u < PKGBUILD.patch || echo "No patches to apply"
            [ -f ".SRCINFO" ] && echo "Deleting .SRCINFO" && rm -f .SRCINFO || echo ".SRCINFO isn't present"

      - name: Build package
        uses: spacefall/actions-makepkg@main
        with:
          dir: ${{inputs.package}}/
          #command: "echo $'[spacefall]\nSigLevel = Never\nServer = https://github.com/spacefall/pacman-repo/releases/latest/download' | sudo tee -a /etc/pacman.conf && sudo pacman -Sy"
          march: skylake
          mtune: skylake
          skipruntimedeps: ${{inputs.skipRuntimeDeps}}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.package}}
          path: ${{inputs.package}}/*.pkg*
