name: Build Package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      isAur:
        required: true
        type: boolean
      skipRuntimeDeps:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Patches
        uses: actions/checkout@v4
        
      - name: Get PKGBUILD - AUR
        if: ${{inputs.isAur}}
        run: git clone https://aur.archlinux.org/${{inputs.package}}.git

      - name: Get PKGBUILD - Arch Gitlab
        if: ${{!inputs.isAur}}
        run: git clone https://gitlab.archlinux.org/archlinux/packaging/packages/${{inputs.package}}.git

      - name: Patch sources
        run: |
            cd ${{inputs.package}}
            [ -f "../${{inputs.package}}-patch/PKGBUILD.patch" ] && cp ../${{inputs.package}}-patch/* . && patch -u < PKGBUILD.patch || echo "No patches to apply"
            [ -f ".SRCINFO" ] && echo "Deleting .SRCINFO" && rm -f .SRCINFO || echo ".SRCINFO isn't present"

      - name: Build package
        uses: spacefall/actions-makepkg@main
        with:
          dir: ${{inputs.package}}/
          command: "echo $'[spacefall]\nSigLevel = Never\nServer = https://github.com/spacefall/pacman-repo/releases/latest/download' | sudo tee -a /etc/pacman.conf && sudo pacman -Sy"
          march: skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -msgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144
          mtune: skylake -dumpbase
          skipruntimedeps: ${{inputs.skipRuntimeDeps}}

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.package}}
          path: ${{inputs.package}}/*.pkg*
