name: Update Packages (build)
concurrency:
  group: build
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  paru:
    uses: ./.github/workflows/builder.yaml
    with:
      package: paru
      
  opentabletdriver:
    uses: ./.github/workflows/builder.yaml
    with:
      package: opentabletdriver
      skipRuntimeDeps: true

  spicetify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-cli
      skipRuntimeDeps: true

  polychromatic:
    uses: ./.github/workflows/builder.yaml
    with:
      package: polychromatic
      skipRuntimeDeps: true

  naps2:
    uses: ./.github/workflows/builder.yaml
    with:
      package: naps2
      skipRuntimeDeps: true

 # hydroxide:
 #   uses: ./.github/workflows/builder.yaml
 #   with:
 #     package: hydroxide-git
 #     skipRuntimeDeps: true

