name: Build Package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      isAur:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Patches
        uses: actions/checkout@v3
        with:
          ref: patches

      - name: Getting PKGBUILD - AUR
        if: ${{inputs.isAur}}
        run: git clone https://aur.archlinux.org/${{inputs.package}}.git

      - name: Getting PKGBUILD - Arch Gitlab
        if: ${{!inputs.isAur}}
        run: git clone https://gitlab.archlinux.org/archlinux/packaging/packages/${{inputs.package}}.git

      - name: Patching sources
        run: |
            cd ${{inputs.package}}
            [ -d "../${{inputs.package}}-patch/" ] && for i in ../${{inputs.package}}-patch/*.patch; do patch -u < $i; done || echo "No patches to apply"
            [ -f ".SRCINFO" ] && echo "Deleting .SRCINFO" && rm -f .SRCINFO || echo ".SRCINFO isn't present"

      - name: Building
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: ${{inputs.package}}/
          srcinfo: true
          aur: true
      #  uses: 2m/arch-pkgbuild-builder@v1.19
      #  with:
      #    target: pkgbuild
      #    pkgname: ${{inputs.package}}/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.package}}
          path: ${{inputs.package}}/*.pkg*
