name: Update Packages (build)
concurrency:
  group: build
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 4 */15 * *"
  workflow_dispatch:

jobs:

  onlyoffice:
    uses: ./.github/workflows/builder.yaml
    with:
      package: onlyoffice
      maxSpace: true

  #prismlauncher:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: prismlauncher
      
  paru:
    uses: ./.github/workflows/builder.yaml
    with:
      package: paru
      
  opentabletdriver:
    uses: ./.github/workflows/builder.yaml
    with:
      package: opentabletdriver
      skipRuntimeDeps: true

  spicetify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-cli-git
      skipRuntimeDeps: true

  polychromatic:
    uses: ./.github/workflows/builder.yaml
    with:
      package: polychromatic
      skipRuntimeDeps: true

 # hydroxide:
 #   uses: ./.github/workflows/builder.yaml
 #   with:
 #     package: hydroxide-git
 #     skipRuntimeDeps: true

