name: Update Gnome Extensions
concurrency:
  group: exts
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 5 1 * *"
  #push: 
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
      
  rounded-windows:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-rounded-window-corners-reborn-git
      isAur: true
      skipRuntimeDeps: true

  hot-edge:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-hot-edge-git
      isAur: true
      skipRuntimeDeps: true

  blur-my-shell:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-blur-my-shell-git
      isAur: true
      skipRuntimeDeps: false

  caffeine:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-caffeine-git
      isAur: true
      skipRuntimeDeps: false

  appindicator:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-appindicator-git
      isAur: true
      skipRuntimeDeps: true

  fuzzy-search:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-fuzzy-app-search-git
      isAur: true
      skipRuntimeDeps: true

  just-perfection:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-just-perfection-desktop-git
      isAur: true
      skipRuntimeDeps: false

  panel-corners:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-panel-corners-git
      isAur: true
      skipRuntimeDeps: false

  qstweaks:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-quick-settings-tweaks-git
      isAur: true
      skipRuntimeDeps: false

  search-light:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-search-light-git
      isAur: true
      skipRuntimeDeps: true

  pano:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-pano-git
      isAur: true
      skipRuntimeDeps: true

  gpu:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-gpu-profile-selector-git
      isAur: true
      skipRuntimeDeps: false

