name: Update Packages
concurrency:
  group: build
  cancel-in-progress: true
on:
  schedule:
    - cron: "30 0 * * 0,4"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  
  # Builds - Electron ----------------------------
  
  bitwarden:
    uses: ./.github/workflows/builder.yaml
    with:
      package: bitwarden
      isAur: false
      skipRuntimeDeps: false

  vesktop:
    uses: ./.github/workflows/builder.yaml
    with:
      package: vencord-desktop-git
      isAur: true
      skipRuntimeDeps: true

  #authy:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: authy-electron
  #    isAur: true
  #    skipRuntimeDeps: true
      
  # Builds - Normal ----------------------------
  
  #spicetify:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: spicetify-cli-git
  #    isAur: true
  #    skipRuntimeDeps: true

  prismlauncher:
    uses: ./.github/workflows/builder.yaml
    with:
      package: prismlauncher
      isAur: true
      skipRuntimeDeps: false

  #electron:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: electron-bin
  #    isAur: true
  #    skipRuntimeDeps: true

  gradience:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gradience-git
      isAur: true
      skipRuntimeDeps: false

  #extension-manager:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: extension-manager
  #    isAur: true
  #    skipRuntimeDeps: false

  # Repacks ------------------------------------------

  #upscayl:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: upscayl-rpm-bin
  #    isAur: true
  #    skipRuntimeDeps: true

  #freefilesync:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: freefilesync-bin
  #    isAur: true
  #    skipRuntimeDeps: true
  
  #spicetify-marketplace:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: spicetify-marketplace-bin
  #    isAur: true
  #    skipRuntimeDeps: true

  # brave:
  #   uses: ./.github/workflows/builder.yaml
  #   with:
  #     package: brave-nightly-bin
  #     isAur: true
  #     skipRuntimeDeps: true
  
  #vscode:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: visual-studio-code-bin
  #    isAur: true
  #    skipRuntimeDeps: true

  #electron-pkg:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: electron28-bin
  #    isAur: true
  #    skipRuntimeDeps: true

  #spotify:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: spotify-snapstore
  #    isAur: true
  #    skipRuntimeDeps: false

  #naps2:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: naps2-bin
  #    isAur: true
  #    skipRuntimeDeps: true
    
  # Deps ---------------------------------------------

  python-libsass:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-libsass
      isAur: true
      skipRuntimeDeps: false

  python-cssutils:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-cssutils
      isAur: true
      skipRuntimeDeps: false

  python-material-color-utilities:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-material-color-utilities
      isAur: true
      skipRuntimeDeps: false
      
  # ---------------------------------------------

  publish:
    runs-on: ubuntu-latest
    needs: [python-material-color-utilities, python-cssutils, python-libsass, vesktop, prismlauncher, gradience, bitwarden]
    if: always() && !cancelled()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          path: built-pkgs/

      # from https://github.com/fwcd/arch-repo/blob/main/.github/workflows/build.yml
      - name: Preparing package database
        run: |
            mkdir repo
            cd built-pkgs/
            mv */*.pkg.tar.zst ../repo/
            cd ..
            
      - name: Building package database
        uses: spacefall/actions-makepkg@pkg-db
        with:
          dir: repo/
          reponame: spacefall

      - name: Publish release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(date '+%Y-%m-%d-%H-%M')"
          gh release create "$tag" --title "$tag" --notes "" repo/*
  
