name: Update Packages
on:
  push:
    branches: [ "patches" ]
  pull_request:
    branches: [ "patches" ]
  workflow_dispatch:

jobs:
  vscodium-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Patches
        uses: actions/checkout@v3
        with:
          ref: patches

      - name: Getting PKGBUILD
        run: git clone https://aur.archlinux.org/${{github.job}}.git

      - name: Patching sources
        run: |
            cd ${{github.job}}
            if [ -d "../${{github.job}}-patch/" ]; then
                for i in ../${{github.job}}-patch/*.patch; do 
                    patch -u < $i
                done
            else 
                echo "No patches to apply"
            fi

      - name: Building
        uses: 2m/arch-pkgbuild-builder@v1.19
        with:
          target: pkgbuild
          pkgname: ${{github.job}}/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.job}}
          path: ${{github.job}}/*.pkg*

  discord-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Patches
        uses: actions/checkout@v3
        with:
          ref: patches

      - name: Getting PKGBUILD
        run: git clone https://aur.archlinux.org/${{github.job}}.git

      - name: Patching sources
        run: |
            cd ${{github.job}}
            [ -d "../${{github.job}}-patch/" ] && for i in ../${{github.job}}-patch/*.patch; do patch -p1 < $i; done

      - name: Building
        uses: 2m/arch-pkgbuild-builder@v1.19
        with:
          target: pkgbuild
          pkgname: ${{github.job}}/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.job}}
          path: ${{github.job}}/*.pkg*

      
