name: Update Packages
on:
  schedule:
    - cron: "0 0 * * 0,4"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  #vscodium:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: vscodium-electron
  #    isAur: true

  #discord:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: vencord-desktop-git
  #    isAur: true
  testing-aur:
    uses: ./.github/workflows/builder.yaml
    with:
      package: c-lolcat
      isAur: true
  
  #bitwarden:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: bitwarden
  #    isAur: false

  #spotify:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: spotify-snapstore
  #    isAur: true

  publish:
    runs-on: ubuntu-latest
    needs: testing-aur
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
    
      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          path: built-pkgs/

      # from https://github.com/fwcd/arch-repo/blob/main/.github/workflows/build.yml
      - name: Build package database
        run: |
            mkdir repo
            cd built-pkgs/
            mv */*.pkg.tar.zst ../repo/
            cd ..
            docker run --rm --user "$(id -u):$(id -g)" --mount type=bind,src="$PWD",dst="/src/${{ github.repository }}" --workdir "/src/${{ github.repository }}" ghcr.io/fwcd/archlinux ./create-db

      - name: Publish release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(date '+%Y-%m-%d-%H-%M')"
          gh release create "$tag" --title "$tag" --notes "" repo/*
  
  #testing-archrepo:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: lolcat
  #    isAur: false
      

