name: Update Packages
concurrency:
  group: build
  cancel-in-progress: true
on:
  schedule:
    - cron: "30 14 * * 1,3,5"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  vscode:
    uses: ./.github/workflows/builder.yaml
    with:
      package: visual-studio-code-bin
      isAur: true
      skipRuntimeDeps: true
  
  authy:
    uses: ./.github/workflows/builder.yaml
    with:
      package: authy-electron
      isAur: true
      skipRuntimeDeps: true
  
  electron:
    uses: ./.github/workflows/builder.yaml
    with:
      package: electron-bin
      isAur: true
      skipRuntimeDeps: true
    
  electron-pkg:
    uses: ./.github/workflows/builder.yaml
    with:
      package: electron27-bin
      isAur: true
      skipRuntimeDeps: true

  vesktop:
    uses: ./.github/workflows/builder.yaml
    with:
      package: vencord-desktop-git
      isAur: true
      skipRuntimeDeps: true

  bitwarden:
    uses: ./.github/workflows/builder.yaml
    with:
      package: bitwarden
      isAur: false
      skipRuntimeDeps: false

  # Non electron packages ----------------------------
  
  brave:
    uses: ./.github/workflows/builder.yaml
    with:
      package: brave-nightly-bin
      isAur: true
      skipRuntimeDeps: true

  spotify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spotify-snapstore
      isAur: true
      skipRuntimeDeps: false
  
  prismlauncher:
    uses: ./.github/workflows/builder.yaml
    with:
      package: prismlauncher
      isAur: true
      skipRuntimeDeps: false

  spicetify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-cli-git
      isAur: true
      skipRuntimeDeps: true

  spicetify-marketplace:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-marketplace-bin
      isAur: true
      skipRuntimeDeps: true
  
  freefilesync:
    uses: ./.github/workflows/builder.yaml
    with:
      package: freefilesync-bin
      isAur: true
      skipRuntimeDeps: true

  upscayl:
    uses: ./.github/workflows/builder.yaml
    with:
      package: upscayl-rpm-bin
      isAur: true
      skipRuntimeDeps: true

  publish:
    runs-on: ubuntu-latest
    needs: [spotify, bitwarden, vesktop, prismlauncher, authy, brave, spicetify, spicetify-marketplace, freefilesync, upscayl, electron, electron-pkg, vscode]
    if: always() && !cancelled()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          path: built-pkgs/

      # from https://github.com/fwcd/arch-repo/blob/main/.github/workflows/build.yml
      - name: Preparing package database
        run: |
            mkdir repo
            cd built-pkgs/
            mv */*.pkg.tar.zst ../repo/
            cd ..

#docker run --rm --user "$(id -u):$(id -g)" --mount type=bind,src="$PWD",dst="/src/${{ github.repository }}" --workdir "/src/${{ github.repository }}" ghcr.io/fwcd/archlinux ./create-db
      
      - name: Building package database
        uses: spacefall/actions-makepkg@pkg-db
        with:
          dir: repo/
          reponame: spacefall

      - name: Publish release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(date '+%Y-%m-%d-%H-%M')"
          gh release create "$tag" --title "$tag" --notes "" repo/*
  
