name: Update Packages
concurrency:
  group: build
  cancel-in-progress: true
on:
  schedule:
    - cron: "30 0 * * 0,4"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  
  # Builds - Electron ----------------------------
  
  bitwarden:
    uses: ./.github/workflows/builder.yaml
    with:
      package: bitwarden
      isAur: false
      skipRuntimeDeps: false

  vesktop:
    uses: ./.github/workflows/builder.yaml
    with:
      package: vencord-desktop-git
      isAur: true
      skipRuntimeDeps: true
      
  # Builds - Normal ----------------------------

  prismlauncher:
    uses: ./.github/workflows/builder.yaml
    with:
      package: prismlauncher
      isAur: true
      skipRuntimeDeps: false

  gradience:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gradience-git
      isAur: true
      skipRuntimeDeps: false
  
  blackbox:
    uses: ./.github/workflows/builder.yaml
    with:
      package: blackbox-terminal
      isAur: true
      skipRuntimeDeps: false

  opentabletdriver:
    uses: ./.github/workflows/builder.yaml
    with:
      package: opentabletdriver
      isAur: true
      skipRuntimeDeps: true
    
  # Repacks ---------------------------------------

  spicetify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-cli-git
      isAur: true
      skipRuntimeDeps: true

  spicetify-marketplace:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-marketplace-bin
      isAur: true
      skipRuntimeDeps: true

  waterfox:
    uses: ./.github/workflows/builder.yaml
    with:
      package: waterfox
      isAur: true
      skipRuntimeDeps: true
      
  betterbird:
    uses: ./.github/workflows/builder.yaml
    with:
      package: betterbird-it-bin
      isAur: true
      skipRuntimeDeps: false

  # Deps ---------------------------------------------

  python-libsass:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-libsass
      isAur: true
      skipRuntimeDeps: false

  python-cssutils:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-cssutils
      isAur: true
      skipRuntimeDeps: true

  python-material-color-utilities:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-material-color-utilities
      isAur: true
      skipRuntimeDeps: true

  libpqmarble:
    uses: ./.github/workflows/builder.yaml
    with:
      package: libpqmarble
      isAur: true
      skipRuntimeDeps: false
      
  # ---------------------------------------------

  publish:
    runs-on: ubuntu-latest
    needs: [betterbird, waterfox, spicetify-marketplace, opentabletdriver, spicetify, python-material-color-utilities, python-cssutils, python-libsass, vesktop, prismlauncher, gradience, bitwarden, libpqmarble, blackbox]
    if: always() && !cancelled()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          path: built-pkgs/

      # from https://github.com/fwcd/arch-repo/blob/main/.github/workflows/build.yml
      - name: Preparing package database
        run: |
            mkdir repo
            cd built-pkgs/
            mv */*.pkg.tar.zst ../repo/
            cd ..
            
      - name: Building package database
        uses: spacefall/actions-makepkg@pkg-db
        with:
          dir: repo/
          reponame: spacefall

      - name: Publish release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(date '+%Y-%m-%d-%H-%M')"
          gh release create "$tag" --title "$tag" --notes "" repo/*
  
