name: Update Packages
on:
  push:
    branches: [ "patches" ]
  pull_request:
    branches: [ "patches" ]
  workflow_dispatch:

jobs:
  vscodium:
    uses: spacefall/pacman-repo/.github/workflows/builder.yml@main
    with:
      package: vscodium-electron

  discord:
    uses: spacefall/pacman-repo/.github/workflows/builder.yml@main
    with:
      package: vscodium-electron

      
