name: Update Packages
concurrency:
  group: build
  cancel-in-progress: true
on:
  #schedule:
  #  - cron: "30 0 * * 0,4"
  #push: 
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  
  # Builds - Electron ----------------------------
  
  #bitwarden:
  #  uses: ./.github/workflows/builder.yaml
  #  with:
  #    package: bitwarden
  #    isAur: false
  #    skipRuntimeDeps: false

  vesktop:
    uses: ./.github/workflows/builder.yaml
    with:
      package: vesktop
      isAur: true
      skipRuntimeDeps: true
      
  # Builds - Normal ----------------------------

  prismlauncher:
    uses: ./.github/workflows/builder.yaml
    with:
      package: prismlauncher
      isAur: true
      skipRuntimeDeps: false

  gradience:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gradience-git
      isAur: true
      skipRuntimeDeps: false
  
  blackbox:
    uses: ./.github/workflows/builder.yaml
    with:
      package: blackbox-terminal
      isAur: true
      skipRuntimeDeps: false

  opentabletdriver:
    uses: ./.github/workflows/builder.yaml
    with:
      package: opentabletdriver
      isAur: true
      skipRuntimeDeps: true
    
  # Repacks ---------------------------------------

  spicetify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-cli-git
      isAur: true
      skipRuntimeDeps: true

  spicetify-marketplace:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-marketplace-bin
      isAur: true
      skipRuntimeDeps: true

  waterfox:
    uses: ./.github/workflows/builder.yaml
    with:
      package: waterfox-bin
      isAur: true
      skipRuntimeDeps: true
      
  betterbird:
    uses: ./.github/workflows/builder.yaml
    with:
      package: betterbird-it-bin
      isAur: true
      skipRuntimeDeps: false

  spotify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spotify
      isAur: true
      skipRuntimeDeps: true

  extension-manager:
    uses: ./.github/workflows/builder.yaml
    with:
      package: extension-manager
      isAur: true
      skipRuntimeDeps: true

  sevenzip:
    uses: ./.github/workflows/builder.yaml
    with:
      package: 7-zip-full
      isAur: false
      skipRuntimeDeps: true

  # Deps ---------------------------------------------

  python-libsass:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-libsass
      isAur: true
      skipRuntimeDeps: false

  text-engine:
    uses: ./.github/workflows/builder.yaml
    with:
      package: text-engine
      isAur: true
      skipRuntimeDeps: false

  polychromatic:
    uses: ./.github/workflows/builder.yaml
    with:
      package: polychromatic
      isAur: true
      skipRuntimeDeps: true

  vscode:
    uses: ./.github/workflows/builder.yaml
    with:
      package: visual-studio-code-bin
      isAur: true
      skipRuntimeDeps: true

  python-cssutils:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-cssutils
      isAur: true
      skipRuntimeDeps: true

  python-material-color-utilities:
    uses: ./.github/workflows/builder.yaml
    with:
      package: python-material-color-utilities
      isAur: true
      skipRuntimeDeps: true

  libpqmarble:
    uses: ./.github/workflows/builder.yaml
    with:
      package: libpqmarble
      isAur: true
      skipRuntimeDeps: false

  libbacktrace:
    uses: ./.github/workflows/builder.yaml
    with:
      package: libbacktrace-git
      isAur: true
      skipRuntimeDeps: true

  # gnome extensions ----------------------------
      
  rounded-windows:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-rounded-window-corners-git
      isAur: true
      skipRuntimeDeps: true

  hot-edge:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-hot-edge-git
      isAur: true
      skipRuntimeDeps: true

  blur-my-shell:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-blur-my-shell-git
      isAur: true
      skipRuntimeDeps: false

  caffeine:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-caffeine-git
      isAur: true
      skipRuntimeDeps: false

  appindicator:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-appindicator-git
      isAur: true
      skipRuntimeDeps: true

  fuzzy-search:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-fuzzy-app-search-git
      isAur: true
      skipRuntimeDeps: true

  just-perfection:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-just-perfection-desktop-git
      isAur: true
      skipRuntimeDeps: false

  panel-corners:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-panel-corners-git
      isAur: true
      skipRuntimeDeps: false

  qstweaks:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-quick-settings-tweaks-git
      isAur: true
      skipRuntimeDeps: false

  search-light:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-search-light-git
      isAur: true
      skipRuntimeDeps: true

  pano:
    uses: ./.github/workflows/builder.yaml
    with:
      package: gnome-shell-extension-pano-git
      isAur: true
      skipRuntimeDeps: true
#---------------------------------------------

  publish:
    runs-on: ubuntu-latest
    needs: [vscode, libbacktrace, polychromatic, sevenzip, text-engine, extension-manager, spotify, pano, qstweaks, search-light, panel-corners, just-perfection, fuzzy-search, appindicator, caffeine, blur-my-shell, hot-edge, rounded-windows, betterbird, waterfox, spicetify-marketplace, opentabletdriver, spicetify, python-material-color-utilities, python-cssutils, python-libsass, vesktop, prismlauncher, gradience, libpqmarble, blackbox]
    if: always() && !cancelled()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          path: built-pkgs/

      # from https://github.com/fwcd/arch-repo/blob/main/.github/workflows/build.yml
      - name: Preparing package database
        run: |
            mkdir repo
            cd built-pkgs/
            mv */*.pkg.tar.zst ../repo/
            cd ..
            
      - name: Building package database
        uses: spacefall/actions-makepkg@pkg-db
        with:
          dir: repo/
          reponame: spacefall

      - name: Publish release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(date '+%Y-%m-%d-%H-%M')"
          gh release create "$tag" --title "$tag" --notes "" repo/*
  
