name: Update Packages (repack)
concurrency:
  group: repack
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 6 */25 * *"
  #push: 
  #  branches:
  #    - main
  workflow_dispatch:

jobs:

  spicetify-marketplace:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spicetify-marketplace-bin
      skipRuntimeDeps: true

  betterbird:
    uses: ./.github/workflows/builder.yaml
    with:
      package: betterbird-it-bin

  spotify:
    uses: ./.github/workflows/builder.yaml
    with:
      package: spotify
      skipRuntimeDeps: true
      
  vscode:
    uses: ./.github/workflows/builder.yaml
    with:
      package: visual-studio-code-bin
      skipRuntimeDeps: true

  jetbrains:
    uses: ./.github/workflows/builder.yaml
    with:
      package: jetbrains-toolbox
      skipRuntimeDeps: true
 
  thorium:
    uses: ./.github/workflows/builder.yaml
    with:
      package: thorium-browser-bin
      skipRuntimeDeps: true
